Repository Scarlet-Engine-Team-GameDev-McGill/Scarlet-Engine, pull requests merged in 2021-04, with the labels that each got.

#87 Fixed issue with check in non-debug builds
  ScarletEngine/Sources/Core/Public/CoreUtils.h
Labels: bug fix

#90 Feature/system rework
  EngineTests/ECS/Registry.cpp
  ScarletEditor/Sources/Editor/Private/EditorViewport.cpp
  ScarletEngine/Sources/Core/Public/CorePCH.h
  ScarletEngine/Sources/ECS/Private/SystemScheduler.cpp
  ScarletEngine/Sources/ECS/Public/Registry.h
  ScarletEngine/Sources/ECS/Public/System.h
  ScarletEngine/Sources/ECS/Public/SystemScheduler.h
  ScarletEngine/Sources/Gameplay/Private/World.cpp
  ScarletEngine/Sources/Gameplay/Public/World.h
  ScarletEngine/Sources/Renderer/CMakeLists.txt
  ScarletEngine/Sources/Renderer/Private/RenderModule.cpp
  ScarletEngine/Sources/Renderer/Private/RenderSystem.h
Labels: core, enhancement

#97 Fixed overlapping grid lines in editor viewport
  ScarletEditor/Sources/Editor/Private/EditorViewport.cpp
  ScarletEngine/Sources/OpenGLRAL/Private/OpenGLRAL.cpp
  ScarletEngine/Sources/Renderer/Private/RenderModule.cpp
Labels: bug fix

#98 Removed instances where target folder was defined on an interface
  ScarletEngine/Thirdparty/IconFontCppHeaders/CMakeLists.txt
  ScarletEngine/Thirdparty/glm/CMakeLists.txt
  ScarletEngine/Thirdparty/stb_image/CMakeLists.txt
Labels: bug fix

#94 Feature/registry rework
  EngineTests/ECS/Registry.cpp
  ScarletEditor/Sources/Editor/Private/Editor.cpp
  ScarletEditor/Sources/Editor/Private/EditorViewport.cpp
  ScarletEditor/Sources/Editor/Public/Editor.h
  ScarletEditor/Sources/PropertyEditor/Private/PropertyEditor.cpp
  ScarletEditor/Sources/PropertyEditor/Public/PropertyEditor.h
  ScarletEditor/Sources/SceneGraph/Private/SceneGraph.cpp
  ScarletEditor/Sources/SceneGraph/Private/SceneGraphItem.cpp
  ScarletEditor/Sources/SceneGraph/Public/SceneGraphItem.h
  ScarletEngine/Sources/ECS/Public/ComponentContainer.h
  ScarletEngine/Sources/ECS/Public/ECS.h
  ScarletEngine/Sources/ECS/Public/Entity.h
  ScarletEngine/Sources/ECS/Public/Registry.h
  ScarletEngine/Sources/ECS/Public/System.h
  ScarletEngine/Sources/ECS/Public/TypeInfo.h
  ScarletEngine/Sources/Gameplay/Public/EntityHandle.h
  ScarletEngine/Sources/Gameplay/Public/World.h
Labels: core, enhancement

#93 Feature/module rework
  ScarletEngine/Sources/Core/Private/IModule.cpp
  ScarletEngine/Sources/Core/Private/ModuleManager.cpp
  ScarletEngine/Sources/Core/Public/CorePCH.h
  ScarletEngine/Sources/Core/Public/IModule.h
  ScarletEngine/Sources/Core/Public/ModuleManager.h
  ScarletEngine/Sources/ECS/Public/System.h
  ScarletEngine/Sources/ECS/Public/SystemScheduler.h
  ScarletEngine/Sources/Engine/Private/Engine.cpp
Labels: core, enhancement

#95 Feature/transform input
  ScarletEditor/Sources/PropertyEditor/Private/PropertyEditor.cpp
  ScarletEngine/Sources/UI/Private/Widgets.cpp
  ScarletEngine/Sources/UI/Public/Widgets.h
Labels: enhancement, tools

#100 Feature/ral commands
  GenerateProjectFiles.bat
  ScarletEngine/Sources/Core/Public/CorePCH.h
  ScarletEngine/Sources/Core/Public/CoreSTL.h
  ScarletEngine/Sources/ECS/Public/System.h
  ScarletEngine/Sources/OpenGLRAL/Private/OpenGLCommandList.h
  ScarletEngine/Sources/OpenGLRAL/Private/OpenGLRAL.cpp
  ScarletEngine/Sources/OpenGLRAL/Private/OpenGLResources.cpp
  ScarletEngine/Sources/OpenGLRAL/Private/OpenGLResources.h
  ScarletEngine/Sources/OpenGLRAL/Public/OpenGLRAL.h
  ScarletEngine/Sources/RAL/Private/RAL.cpp
  ScarletEngine/Sources/RAL/Public/RAL.h
  ScarletEngine/Sources/RAL/Public/RALCommandList.h
  ScarletEngine/Sources/Renderer/Private/RenderModule.cpp
  ScarletEngine/Sources/UI/Private/UIModule.cpp
Labels: enhancement, rendering

#101 Removed concepts and ranges
  ScarletEngine/Sources/Core/Public/CorePCH.h
  ScarletEngine/Sources/ECS/Public/System.h
  ScarletEngine/Sources/OpenGLRAL/Private/OpenGLResources.cpp
  ScarletEngine/Sources/RAL/Public/RALCommandList.h
Labels: bug fix

#99 Feature/physics - Collision and Spring System
  ScarletEditor/CMakeLists.txt
  ScarletEditor/Sources/EditorMain.cpp
  ScarletEngine/CMakeLists.txt
  ScarletEngine/Content/Plane.obj
  ScarletEngine/Content/Sphere.obj
  ScarletEngine/Shaders/test_shader.frag
  ScarletEngine/Sources/AchillesPhysics/CMakeLists.txt
  ScarletEngine/Sources/AchillesPhysics/Private/ColliderSystem.cpp
  ScarletEngine/Sources/AchillesPhysics/Private/RigidBodySystem.cpp
  ScarletEngine/Sources/AchillesPhysics/Private/SpringSystem.cpp
  ScarletEngine/Sources/AchillesPhysics/Public/AchillesCore.h
  ScarletEngine/Sources/AchillesPhysics/Public/AchillesDemo.h
  ScarletEngine/Sources/AchillesPhysics/Public/ColliderComponent.h
  ScarletEngine/Sources/AchillesPhysics/Public/ColliderSystem.h
  ScarletEngine/Sources/AchillesPhysics/Public/RigidBodyComponent.h
  ScarletEngine/Sources/AchillesPhysics/Public/RigidBodySystem.h
  ScarletEngine/Sources/AchillesPhysics/Public/SpringComponent.h
  ScarletEngine/Sources/AchillesPhysics/Public/SpringSystem.h
  ScarletEngine/Sources/AchillesPhysics/README.md
  ScarletEngine/Sources/Engine/Private/Engine.cpp
  ScarletEngine/Sources/Engine/Public/Engine.h
  ScarletEngine/Sources/Gameplay/Public/World.h
  ScarletEngine/Sources/Window/Private/Window.cpp
Labels: physics
